# Generated by Django 4.1.6 on 2023-02-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='용어')),
                ('content', models.TextField(verbose_name='설명')),
                ('tstamp', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '사전',
                'verbose_name_plural': '사전',
                'db_table': 'shinhan_dictionary',
            },
        ),
    ]
