# Generated by Django 4.1.6 on 2023-02-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticnews',
            name='img',
            field=models.URLField(default='', max_length=500, verbose_name='뉴스 이미지'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overseasnews',
            name='img',
            field=models.URLField(default='', max_length=500, null=True, verbose_name='뉴스 이미지'),
        ),
    ]
