# Generated by Django 4.1.6 on 2023-02-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_domesticnews_img_overseasnews_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticnews',
            name='img',
            field=models.URLField(default='', max_length=500, null=True, verbose_name='뉴스 이미지'),
        ),
    ]
