# Generated by Django 4.1.6 on 2023-02-19 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='용어')),
                ('content', models.TextField(verbose_name='설명')),
                ('tstamp', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 단어장',
                'verbose_name_plural': '사용자 단어장',
                'db_table': 'shinhan_member_note',
            },
        ),
    ]
