# Generated by Django 4.1.6 on 2023-02-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=128, verbose_name='용어'),
        ),
    ]
