# Generated by Django 4.1.6 on 2023-02-22 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0005_note_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note', verbose_name='단어')),
            ],
            options={
                'verbose_name': '단어 즐겨찾기',
                'verbose_name_plural': '단어 즐겨찾기',
                'db_table': 'shinhan_bookmark',
            },
        ),
    ]
